  GNU nano 4.8                                                /root/realworld-docker/frontend/Dockerfile
FROM node:13.12.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

